export enum BadgeCriteria {
  COURSE_COMPLETE = 'COURSE_COMPLETE',
  PERFECT_QUIZ = 'PERFECT_QUIZ',
  FIRST_ENROLLMENT = 'FIRST_ENROLLMENT',
  STREAK = 'STREAK',
  MANUAL = 'MANUAL',
  LEVEL_UP = 'LEVEL_UP',
}
