export enum NotificationType {
  GRADE_POSTED = 'GRADE_POSTED',
  BADGE_EARNED = 'BADGE_EARNED',
  ENROLLMENT_APPROVED = 'ENROLLMENT_APPROVED',
  ENROLLMENT_REJECTED = 'ENROLLMENT_REJECTED',
  NEW_LESSON = 'NEW_LESSON',
  ASSIGNMENT_DUE_SOON = 'ASSIGNMENT_DUE_SOON',
  FORUM_REPLY = 'FORUM_REPLY',
  SYSTEM = 'SYSTEM',
}
